### ISSUE TITLE
Option to use real dates for start and end

### ISSUE THREAD

**Issue by mattbk** [giocomai/ganttrify#1]
This project looks really great in the examples, but do you think there will eventually be an option to pass dates for start/end rather than month durations?

**Comment by giocomai** [comment]
Do you mean, setting the start and end month, with something like "2020-10" for October 2020 (instead of the number of the month since the beginning of the project), or have the whole timeline based on days, where one could input say "2020-10-22" to "2020-11-17"? Or something else?

Either way, it shouldn't be a problem, so it will probably be possible soon.

**Comment by mattbk** [comment]
> have the whole timeline based on days, where one could input say "2020-10-22" to "2020-11-17"

This is what I mean. I'm not trying to add extra work for you, but I thought others might have the same feature request.

**Comment by giocomai** [comment]
No worries, I was about to include it as a project output and was working on adding some features anyway (check out the updated readme for details). I hope this works for your use case. I may eventually add support for very short periods (e.g. conference programmes) or very long periods (historical periods), but for the time being this is tailored to work for medium timeframe (between a few months and a couple of years), which is what I feel is mostly needed as Gantt chart. 

``` r
library("ganttrify")

knitr::kable(ganttrify::test_project_date_day)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">wp</th>
<th style="text-align: left;">activity</th>
<th style="text-align: left;">start_date</th>
<th style="text-align: left;">end_date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Data team</td>
<td style="text-align: left;">Data collection</td>
<td style="text-align: left;">2020-09-01</td>
<td style="text-align: left;">2020-09-10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data team</td>
<td style="text-align: left;">Data processing</td>
<td style="text-align: left;">2020-09-08</td>
<td style="text-align: left;">2020-09-14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Data team</td>
<td style="text-align: left;">Reporting</td>
<td style="text-align: left;">2020-09-14</td>
<td style="text-align: left;">2020-09-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data team</td>
<td style="text-align: left;">Data visualisation</td>
<td style="text-align: left;">2020-10-23</td>
<td style="text-align: left;">2020-10-30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Investigative team</td>
<td style="text-align: left;">Fieldwork</td>
<td style="text-align: left;">2020-09-05</td>
<td style="text-align: left;">2020-09-15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Investigative team</td>
<td style="text-align: left;">Fieldwork</td>
<td style="text-align: left;">2020-10-10</td>
<td style="text-align: left;">2020-10-20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Investigative team</td>
<td style="text-align: left;">Writing</td>
<td style="text-align: left;">2020-10-21</td>
<td style="text-align: left;">2020-10-31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Social media team</td>
<td style="text-align: left;">Draft outputs</td>
<td style="text-align: left;">2020-10-25</td>
<td style="text-align: left;">2020-10-28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Social media team</td>
<td style="text-align: left;">Active promo</td>
<td style="text-align: left;">2020-10-31</td>
<td style="text-align: left;">2020-12-15</td>
</tr>
</tbody>
</table>

``` r

ganttrify(project = ganttrify::test_project_date_day,
          spots = ganttrify::test_spots_date_day,
          by_date = TRUE,
          exact_date = TRUE)
```

![](https://i.imgur.com/713Yoq1.png)

<sup>Created on 2020-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattbk** [comment]
Thanks for this!

I am running into an error, might be my version of ggplot2? I am running 3.3.0 on R 3.5.

Running your example:
```
ganttrify(project = ganttrify::test_project_date_day,
          spots = ganttrify::test_spots_date_day,
          by_date = TRUE,
          exact_date = TRUE)
```

I get:
`Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found`

**Comment by giocomai** [comment]
The error message is not really helpful, but most probably this refers to a missing font. I used "Roboto Condensed" as default, as narrow/condensed fonts use text space more efficiently. On my machines, if the font was not found it just threw a warning, but still spit out the graph with a default font.

You can probably fix this just by adding the parameter `font_family = "sans"`.

However, since this may well be a problem for many, I changed the default to `sans` which is always available, and added more details in the readme. 

If you update the package, things should work for you (of course, you'll have the graph with a generic sans font). 

Please let me know if this works for you. 

There is also now a [hosted version of the shiny app](https://ganttrify.giorgiocomai.eu/) that ships with the package, and it includes all fonts as well as the libraries for exporting to pdf and svg that may be missing on some systems.

**Comment by mattbk** [comment]
Can confirm that it works now with a generic font. Thanks!
